[workspace]

members = [
    "client_macros",
    "server_macros",
    "client_home",
    "client_sdk",
    "server"
]

[profile.release.package.client_home]
opt-level = "z"
strip = "debuginfo"
codegen-units = 1