[config]
default_to_workspace = false

[env]
RUST_BACKTRACE = 0

[tasks.clean]
dependencies = [
    { name = "clean", path = "client" }
]

[tasks.build]
clear = true
dependencies = [
    { name = "build", path = "client" },
    { name = "build", path = "server" },
]

[tasks.run]
clear = true
dependencies = ["build"]
command = "target/release/dndcent"