[config]
default_to_workspace = false

[env]
RUST_BACKTRACE = 0

[tasks.clean]
dependencies = [
    { name = "dist_clean", path = "client" }
]

[tasks.default]
clear = true
dependencies = [
    { name = "build", path = "client" },
    { name = "build", path = "server" },
]

[tasks.release]
dependencies = [
    { name = "build_release", path = "client" },
    { name = "build_release", path = "server" },
]

[tasks.run]
clear = true
dependencies = ["default"]
command = "target/release/dndcent"