[config]
default_to_workspace = false

[env]
RUST_BACKTRACE = 0

[tasks.clean]
dependencies = [
    { name = "dist_clean", path = "client_home" }
]

[tasks.default]
clear = true
dependencies = [
    { name = "build", path = "client_home" },
    { name = "build", path = "server" },
]

[tasks.release]
dependencies = [
    { name = "build_release", path = "client_home" },
    { name = "build_release", path = "server" },
]

[tasks.run]
clear = true
dependencies = ["default"]
command = "target/debug/dndcent"

[tasks.install]
dependencies = [
    { name = "build_release", path = "client_home" }
]
command = "cargo"
args = ["install", "--path", "server"]