[build]
# The index HTML file to drive the bundling process.
target = "index.html"
# Build in release mode.
release = false
# The output dir for all final assets.
dist = "../www/home/"

[clean]
# The output dir for all final assets.
dist = "../www/home"
# Optionally perform a cargo clean.
cargo = true