[tasks.dist_clean]
install_crate = "trunk"
command = "trunk"
args = [ "clean" ]

[tasks.build]
install_crate = "trunk"
command = "trunk"
args = ["build", "${@}"]

[tasks.build_release]
install_crate = "trunk"
command = "trunk"
args = ["build", "--release"]
