[build]
# The index HTML file to drive the bundling process.
target = "index.html"
# Build in release mode.
release = false
# The output dir for all final assets.
dist = "../../www/systems/template"

# why
public_url = "./"

[clean]
# The output dir for all final assets.
dist = "../../www/systems/template"
# Optionally perform a cargo clean.
cargo = true
